

export type Role = 'admin' | 'faculty' | 'student';

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
}

export interface AppEvent {
  id: string; 
  title: string;
  date: string; // ISO string
  description: string;
  type: 'lecture' | 'hackathon' | 'fest' | 'internship_fair' | 'exam' | 'notice';
  image?: string;
  dataAiHint?: string;
}

export interface StudyMaterial {
  id: string;
  title: string;
  description: string;
  subject: string;
  fileType: 'pdf' | 'ppt' | 'doc' | 'link';
  fileName?: string; // For actual file uploads
  fileUrl: string; // Could be a download link or path
  uploadedBy: string; // Faculty name or ID
  uploadDate: string; // ISO string or Date object
}

export interface PlacementOpportunity {
  id: string;
  title: string;
  company: string;
  description: string;
  batchYear?: string; // e.g., "2024", "2025"
  eligibility?: {
    cgpa?: number;
    skills?: string[];
  };
  applyLink: string;
  postedDate: string; // ISO string or Date object
  lastDateToApply?: string;
}

export interface Feedback {
  id:string; 
  studentId?: string; 
  facultyId?: string; 
  courseId?: string;
  feedbackText: string;
  submittedDate: string; // ISO string 
  sentiment?: 'positive' | 'negative' | 'neutral'; // Could be generated by AI
  summary?: string; // Could be generated by AI
}

export interface Class {
  id: string;
  name: string; // e.g., "MCA I Year - Section A"
  academicYear: string; // e.g., "2024-2025"
  inchargeFaculty: string; // Should be a faculty user's ID
}

export interface Subject {
  id: string;
  name: string; // e.g., "Advanced Java"
  code: string; // e.g., "CS-501"
  classId: string; // The ID of the class it belongs to
  facultyId: string; // The ID of the faculty handling the subject
}
